"""Generated responsible-AI cards for the optional drafting seam."""

from __future__ import annotations

from pathlib import Path


def render_model_card() -> str:
    return """# Model card — optional narrative drafter

Generated by `receipts cards`. Do not edit by hand.

## Intended use

When explicitly enabled, Claude on Amazon Bedrock rewrites a filled funder-report
template for clarity. It receives the baseline narrative and an allowlist of
receipted display strings. It does not compute metrics, map fields, approve a
report, or verify a number.

## Policy and enforcement

Cloud drafting is off by default. It requires `provider = "bedrock"`,
`enabled = true`, a pinned `model_id`, and the per-run
`--allow-cloud-drafting` flag. The deterministic drafter remains the default.
Every model draft is grounded against raw receipts, suppression rebuilds the
publishable surfaces, and the publishable draft is grounded again before human
approval. Any added, altered, rounded, signed, ranged, or written-out number
blocks export.

## Limitations and evaluation

The model may change meaning without adding a number, produce poor prose, or fail
to follow the allowlist. Grounding proves numeric provenance, not narrative
quality or fairness. Tests inject an invented number and require the gate to
reject it. A model-based faithfulness judge is not shipped; if added, it must be
calibrated against human labels before gating decisions.

## Human responsibility

A named human approves the final redacted artifact. Approval is not evidence
that the underlying metric definition or source data is correct.
"""


def render_data_card() -> str:
    return """# Data card — reporting and drafting data flow

Generated by `receipts cards`. Do not edit by hand.

## Data

Inputs are organization-provided CSV exports and author-controlled TOML specs.
Fixtures are synthetic. The deterministic engine processes source rows locally
and emits scalar figures with query, row-count, and slice-hash receipts.

## Cloud boundary

By default, no data leaves the process. With Bedrock drafting explicitly enabled,
the request contains only the filled narrative and scalar display allowlist. It
does not contain source rows, client identifiers, receipt hashes, SQL, or data
paths. Small aggregate values may appear in the first in-memory drafting pass;
organizations must authorize that transfer under their own data policy.

## Publication and privacy

Exports are structurally aggregate-only. Counts from 1 through 10 are redacted
under the CMS-modeled default; complementary, delta, and percentage controls
reduce arithmetic recovery. HUD does not prescribe this numeric floor, so the
applicable local policy remains authoritative. True zeros remain visible.

## Retention and limitations

The application does not create a cloud-side retention policy; Amazon Bedrock
account and logging configuration controls provider-side handling. Local source
files, outputs, ledgers, and bundles remain under operator control. Receipts show
how a number was computed, not whether collection was complete, consensual, or
free from structural bias.
"""


def write_cards(out_dir: Path, *, check: bool = False) -> bool:
    """Write generated cards, or return whether committed cards are current."""

    cards = {
        "MODEL-CARD.md": render_model_card(),
        "DATA-CARD.md": render_data_card(),
    }
    if check:
        return all(
            (out_dir / name).exists() and (out_dir / name).read_text(encoding="utf-8") == content
            for name, content in cards.items()
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in cards.items():
        (out_dir / name).write_text(content, encoding="utf-8")
    return True
